### ISSUE TITLE
No benchmark result

### ISSUE THREAD

**Issue by Ingsuifon** [efficient/HOPE#9]
Hi, after executing `./scripts/run_experiments.sh`, there is no results or figures generated in the directories, am I doing something wrong or is there something wrong?

**Comment by LiuXiaoxuanPKU** [comment]
Hi, thanks for your interest! Could you check if there is a result directory generated after running the script? It should be `results` directory under the root directory

**Comment by Ingsuifon** [comment]
Yes, two directories `results` and `figures` are created after executing the command, but all the subdirectories within them are empty.

**Comment by Ingsuifon** [comment]
I found that it must actively choose a test target, such as ` ./scripts/run_experiments.sh --microbench --alm --wiki `, then it will generates the corresponding results. I think the default parameters in `run_experiments.sh`
```
run_microbench=0
run_small_experiment=0
run_alm=0
run_art=0
run_btree=0
run_hot=0
run_surf=0
run_prefixbtree=0
run_email=0
run_wiki=0
run_url=0
```
should be changed to 1.
